manifest:
  version: 0.8

  projects:
    - name: zephyr
      revision: v11.45.14
      url: https://github.com/aokblast/zephyr.git
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis
          - picolibc